
from pybricks.hubs import PrimeHub
from pybricks.pupdevices import Motor, ColorSensor, UltrasonicSensor
from pybricks.parameters import Port
from pybricks.tools import wait

## initialize the motors and sensors
motor_a = Motor(Port.A)
motor_b = Motor(Port.B)
colour_motor = Motor(Port.F)
distance = UltrasonicSensor(Port.C)
colour = ColorSensor(Port.D)

first_turn = True
obstacle_detected = False

def distance_check(repetitions):
    global obstacle_detected
    ## checks for obstacles every 10ms
    ## if obstacle detected set flag to stop everything and output colour
    for reps in range(repetitions):
        if distance.distance() < 45 and distance.distance() !=  -1:
            obstacle_detected = True
            ## slowly approach obstacle to enable better colour identification
            approach = True
            # while approach:
            #     # print(distance.distance())
            #     if distance.distance() > 45:
            #         motor_a.run(-200)
            #         motor_b.run(200)
            #         wait(10)
            #         reps += 1
            #         print("closer", reps)
            #     else:
            #         motor_a.stop()
            #         motor_b.stop()
            #         approach = False
            motor_a.stop()
            motor_b.stop()
            colour_motor.run_target(200, -100)
            wait(500)
            print(f"Obstacle detected is {colour.color()}")
            print(reps)
            if reps > 10:
                for _ in range(reps):
                    motor_a.run(300)
                    motor_b.run(-300)
                    wait(10)
            motor_a.stop()
            motor_b.stop()
            break
        wait(10)


def move_straight():
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.run(-300)
        motor_b.run(300)
        # distance_check(75)
        distance_check(150)
        #print("move straight")

def move_straight_diagonally():
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.run(-300)
        motor_b.run(300)
        # distance_check(106)
        distance_check(212)
        #print("move straight diagonally")

def left_turn():
    global first_turn
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.run(250)
        motor_b.run(250)
        if first_turn == True:
            # distance_check(64)
            wait(640)
            first_turn = False
        else:
            # distance_check(73)
            wait(730)
        #print("left turn")

def right_turn():
    global first_turn
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.run(-250)
        motor_b.run(-250)
        if first_turn == True:
            # distance_check(64)
            wait(640)
            first_turn = False
        else:
            # distance_check(73)
            wait(730)
        #print("right turn")

def left_turn_45():
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.run(250)
        motor_b.run(250)
        # distance_check(40)
        wait(400)
        #print("45 degree left turn")

def right_turn_45():
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.run(-250)
        motor_b.run(-250)
        # distance_check(40)
        wait(400)
        #print("45 degree right turn")

def stop():
    global obstacle_detected
    if obstacle_detected == False:
        motor_a.stop()
        motor_b.stop()
        print("Goal has been reached. Stopping AGV.")


## ensure colour sensor points down
colour_motor.run_target(200, 0)

## movement sequence
movements = [
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    move_straight,
    move_straight,
    right_turn,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    left_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    left_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    right_turn_45,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    move_straight,
    right_turn_45,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    move_straight_diagonally,
    stop,
]
## execute movements until obstacle is detected
for idx, movement in enumerate(movements):
    ## stop executing further movements if obstacle is detected
    if obstacle_detected:
        break
    movement()
print(f'MOVEMENT_PROGRESS: Movement index: {idx}, Total: {len(movements) - 1}')
